# Redirect to https
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-https-redirectscheme
  # namespace: traefik-system
spec:
  redirectScheme:
    scheme: https
    permanent: true
