apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: codesativa
  destination:
    server: https://kubernetes.default.svc
    namespace: codesativa-erp-staging
  source:
    repoURL: git@github.com:starmediateknik/k8s-manifest.git
    path: starmediateknik/erp/staging
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
